# Generated by Django 2.2.17 on 2020-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=123, upload_to='images/'),
            preserve_default=False,
        ),
    ]
